
services:
  rp:
    image: apache-banque:1.0
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - 80:80
    depends_on:
      - tomcat

  tomcat:
    image: tomcat-banque:1.0
    container_name: tomcat-banque
    build: 
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - 8180:8080
    depends_on:
      - mariadb
      
  mariadb:
    image: mariadb-banque:1.0
    container_name: mariadb-banque
    build: 
      context: .
      dockerfile: Dockerfile.mariadb
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
    name: mariadb
    driver: local